title: Moneer Rifai - Cloud Developer
baseURL: /
params:
  color_scheme: light
  accent_color: blue
  header:
    title: Moneer Rifai
    has_nav: true
    has_social: true
  footer:
    content: '&copy; Moneer Rifai. All rights reserved.'
    links:
      - text: Made with ☕ and ❤️ and Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
    has_social: true
disableKinds:
  - RSS
